% Auto-generated by poisson3d/write_matlab
% Usage: from MATLAB, run this script: plot_poisson_u
scriptDir = fileparts(mfilename('fullpath'));
dataFile  = fullfile(scriptDir, 'poisson_u_matlab.bin');
fid = fopen(dataFile, 'rb');
assert(fid > 0, 'Could not open %s', dataFile);
N = fread(fid, 1, 'int32');
u = fread(fid, double(N)^3, 'double');
fclose(fid);
u = reshape(u, [N N N]);

% Basic 3D visualization: isosurface + mid-plane slices
figure('Name','poisson3d: u');
subplot(1,2,1);
iso = 0.5*(min(u(:)) + max(u(:)));
p = patch(isosurface(u, iso));
isonormals(u, p);
set(p, 'FaceColor', [0.2 0.6 0.9], 'EdgeColor', 'none', 'FaceAlpha', 0.6);
daspect([1 1 1]); axis tight; view(3); grid on;
camlight headlight; lighting gouraud;
title(sprintf('Isosurface u = %.3g', iso));

subplot(1,2,2);
k = round(N/2);
imagesc(u(:,:,k)); axis image; colorbar;
title(sprintf('Mid-plane slice k=%d', k));
