% Auto-generated by poisson3d/write_matlab
% Usage: from MATLAB, run this script: plot_poisson_u
scriptDir = fileparts(mfilename('fullpath'));
dataFile  = fullfile(scriptDir, 'poisson_u_matlab.bin');
fid = fopen(dataFile, 'rb');
assert(fid > 0, 'Could not open %s', dataFile);
N = fread(fid, 1, 'int32');
u = fread(fid, double(N)^3, 'double');
fclose(fid);
u = reshape(u, [N N N]);

% Visualization: 2x3 tiledlayout of slices (1/3 and 2/3)
figure('Name','poisson3d: u slices', 'Color', 'w');
t = tiledlayout(2, 3, 'TileSpacing', 'compact', 'Padding', 'compact');

% Slice indices (clamped to [1, N])
i1 = max(1, min(N, round(N/3)));
i2 = max(1, min(N, round(2*N/3)));
j1 = i1; j2 = i2;
k1 = i1; k2 = i2;

% Physical coordinates (assumed domain [-1, 1] in each direction)
x = linspace(-1, 1, N);
y = linspace(-1, 1, N);
z = linspace(-1, 1, N);

% Use a common color scale across all tiles
umin = min(u(:));
umax = max(u(:));
colormap(parula);
fs = 16;

% Row 1: 1/3 slices
nexttile; imagesc(z, y, squeeze(u(i1,:,:))); axis image; axis xy; caxis([umin umax]);
title(sprintf('$x = %.3f\\,[\\mathrm{m}]$', x(i1)), 'Interpreter','latex', 'FontSize', fs);
xlabel('$z \quad [\mathrm{m}]$', 'Interpreter','latex', 'FontSize', fs); ylabel('$y \quad [\mathrm{m}]$', 'Interpreter','latex', 'FontSize', fs);
set(gca, 'TickLabelInterpreter','latex', 'FontSize', fs);

nexttile; imagesc(z, x, squeeze(u(:,j1,:))); axis image; axis xy; caxis([umin umax]);
title(sprintf('$y = %.3f\\,[\\mathrm{m}]$', y(j1)), 'Interpreter','latex', 'FontSize', fs);
xlabel('$z \quad [\mathrm{m}]$', 'Interpreter','latex', 'FontSize', fs); ylabel('$x \quad [\mathrm{m}]$', 'Interpreter','latex', 'FontSize', fs);
set(gca, 'TickLabelInterpreter','latex', 'FontSize', fs);

nexttile; imagesc(y, x, u(:,:,k1)); axis image; axis xy; caxis([umin umax]);
title(sprintf('$z = %.3f\\,[\\mathrm{m}]$', z(k1)), 'Interpreter','latex', 'FontSize', fs);
xlabel('$y \quad [\mathrm{m}]$', 'Interpreter','latex', 'FontSize', fs); ylabel('$x \quad [\mathrm{m}]$', 'Interpreter','latex', 'FontSize', fs);
set(gca, 'TickLabelInterpreter','latex', 'FontSize', fs);

% Row 2: 2/3 slices
nexttile; imagesc(z, y, squeeze(u(i2,:,:))); axis image; axis xy; caxis([umin umax]);
title(sprintf('$x = %.3f\\,[\\mathrm{m}]$', x(i2)), 'Interpreter','latex', 'FontSize', fs);
xlabel('$z \quad [\mathrm{m}]$', 'Interpreter','latex', 'FontSize', fs); ylabel('$y \quad [\mathrm{m}]$', 'Interpreter','latex', 'FontSize', fs);
set(gca, 'TickLabelInterpreter','latex', 'FontSize', fs);

nexttile; imagesc(z, x, squeeze(u(:,j2,:))); axis image; axis xy; caxis([umin umax]);
title(sprintf('$y = %.3f\\,[\\mathrm{m}]$', y(j2)), 'Interpreter','latex', 'FontSize', fs);
xlabel('$z \quad [\mathrm{m}]$', 'Interpreter','latex', 'FontSize', fs); ylabel('$x \quad [\mathrm{m}]$', 'Interpreter','latex', 'FontSize', fs);
set(gca, 'TickLabelInterpreter','latex', 'FontSize', fs);

nexttile; imagesc(y, x, u(:,:,k2)); axis image; axis xy; caxis([umin umax]);
title(sprintf('$z = %.3f\\,[\\mathrm{m}]$', z(k2)), 'Interpreter','latex', 'FontSize', fs);
xlabel('$y \quad [\mathrm{m}]$', 'Interpreter','latex', 'FontSize', fs); ylabel('$x \quad [\mathrm{m}]$', 'Interpreter','latex', 'FontSize', fs);
set(gca, 'TickLabelInterpreter','latex', 'FontSize', fs);

% One shared colorbar for all tiles
cb = colorbar;
cb.Layout.Tile = 'east';
ylabel(cb, 'Temperature $[^{\circ}\mathrm{C}]$', 'Interpreter','latex', 'FontSize', fs);
set(cb, 'TickLabelInterpreter','latex', 'FontSize', fs);

% Save figure to current folder
outPng = fullfile(pwd, 'poisson_sol_slices.png');
if exist('exportgraphics', 'file')
    exportgraphics(gcf, outPng, 'Resolution', 300);
else
    set(gcf, 'PaperPositionMode', 'auto');
    print(gcf, outPng, '-dpng', '-r300');
end
