module write_output
  use precision, only: dp

  implicit none
  private

  public :: write_binary
  public :: write_vtk
  public :: write_matlab

contains

  subroutine check_iostat_local(iostat, msg)
    integer, intent(in) :: iostat
    character(len=*), intent(in) :: msg

    if ( iostat == 0 ) return

    write(*,'(a,i0,/,tr3,a)') 'ERROR = ', iostat, msg
    stop
  end subroutine check_iostat_local

  subroutine write_binary(u)
    real(dp), intent(in) :: u(:,:,:)

    character(len=*), parameter :: filename = 'output/poisson_u.bin'
    integer :: n
    integer :: iostat

    integer, parameter :: unit = 11249

    n = size(u, 1)

    open(unit, file=filename, form='unformatted', access='stream', status='replace', iostat=iostat)
    call check_iostat_local(iostat, "Could not open file '"//filename//"'!")

    write(unit, iostat=iostat) n
    call check_iostat_local(iostat, 'Could not write variable N')

    write(unit, iostat=iostat) u
    call check_iostat_local(iostat, 'Could not write variable u')

    close(unit)
  end subroutine write_binary

  subroutine write_vtk(u)
    use, intrinsic :: iso_c_binding

    interface
      subroutine write_vtk_c(n, u) bind(C, name='write_vtk')
        import c_ptr, c_int
        implicit none
        integer(c_int), value :: n
        type(c_ptr), value :: u
      end subroutine write_vtk_c
    end interface

    real(dp), intent(in), target :: u(:,:,:)

    integer(c_int) :: n

    n = size(u, 1)
    call write_vtk_c(n, c_loc(u(1,1,1)))
  end subroutine write_vtk

  subroutine write_matlab(u)
    use, intrinsic :: iso_fortran_env, only: int32

    real(dp), intent(in) :: u(:,:,:)

    character(len=*), parameter :: data_filename = 'output/poisson_u_matlab.bin'
    character(len=*), parameter :: script_filename = 'output/plot_poisson_u.m'

    integer(int32) :: n
    integer :: iostat

    integer, parameter :: unit_data = 21249
    integer, parameter :: unit_script = 21250

    n = int(size(u, 1), int32)

    ! Write a MATLAB-friendly binary file:
    ! - int32: N
    ! - double: u(:,:,:) in Fortran (column-major) order
    open(unit_data, file=data_filename, form='unformatted', access='stream', status='replace', iostat=iostat)
    call check_iostat_local(iostat, "Could not open file '"//data_filename//"'!")

    write(unit_data, iostat=iostat) n
    call check_iostat_local(iostat, 'Could not write variable N')

    write(unit_data, iostat=iostat) u
    call check_iostat_local(iostat, 'Could not write variable u')

    close(unit_data)

    ! Write a companion MATLAB script that loads and visualizes the 3D field.
    open(unit_script, file=script_filename, action='write', status='replace', iostat=iostat)
    call check_iostat_local(iostat, "Could not open file '"//script_filename//"'!")

    write(unit_script,'(a)') "% Auto-generated by poisson3d/write_matlab"
    write(unit_script,'(a)') "% Usage: from MATLAB, run this script: plot_poisson_u"
    write(unit_script,'(a)') "scriptDir = fileparts(mfilename('fullpath'));"
    write(unit_script,'(a)') "dataFile  = fullfile(scriptDir, 'poisson_u_matlab.bin');"
    write(unit_script,'(a)') "fid = fopen(dataFile, 'rb');"
    write(unit_script,'(a)') "assert(fid > 0, 'Could not open %s', dataFile);"
    write(unit_script,'(a)') "N = fread(fid, 1, 'int32');"
    write(unit_script,'(a)') "u = fread(fid, double(N)^3, 'double');"
    write(unit_script,'(a)') "fclose(fid);"
    write(unit_script,'(a)') "u = reshape(u, [N N N]);"
    write(unit_script,'(a)') ""
    write(unit_script,'(a)') "% Visualization: 2x3 tiledlayout of slices (1/3 and 2/3)"
    write(unit_script,'(a)') "figure('Name','poisson3d: u slices', 'Color', 'w');"
    write(unit_script,'(a)') "t = tiledlayout(2, 3, 'TileSpacing', 'compact', 'Padding', 'compact');"
    write(unit_script,'(a)') ""
    write(unit_script,'(a)') "% Slice indices (clamped to [1, N])"
    write(unit_script,'(a)') "i1 = max(1, min(N, round(N/3)));"
    write(unit_script,'(a)') "i2 = max(1, min(N, round(2*N/3)));"
    write(unit_script,'(a)') "j1 = i1; j2 = i2;"
    write(unit_script,'(a)') "k1 = i1; k2 = i2;"
    write(unit_script,'(a)') ""
    write(unit_script,'(a)') "% Physical coordinates (assumed domain [-1, 1] in each direction)"
    write(unit_script,'(a)') "x = linspace(-1, 1, N);"
    write(unit_script,'(a)') "y = linspace(-1, 1, N);"
    write(unit_script,'(a)') "z = linspace(-1, 1, N);"
    write(unit_script,'(a)') ""
    write(unit_script,'(a)') "% Use a common color scale across all tiles"
    write(unit_script,'(a)') "umin = min(u(:));"
    write(unit_script,'(a)') "umax = max(u(:));"
    write(unit_script,'(a)') "colormap(parula);"
    write(unit_script,'(a)') "fs = 16;"
    write(unit_script,'(a)') ""
    write(unit_script,'(a)') "% Row 1: 1/3 slices"
    write(unit_script,'(a)') "nexttile; imagesc(z, y, squeeze(u(i1,:,:))); axis image; axis xy; caxis([umin umax]);"
    write(unit_script,'(a)') "title(sprintf('$x = %.3f\\,[\\mathrm{m}]$', x(i1)), 'Interpreter','latex', 'FontSize', fs);"
    write(unit_script,'(a)') "xlabel('$z \quad [\mathrm{m}]$', 'Interpreter','latex', 'FontSize', fs); ylabel('$y \quad [\mathrm{m}]$', 'Interpreter','latex', 'FontSize', fs);"
    write(unit_script,'(a)') "set(gca, 'TickLabelInterpreter','latex', 'FontSize', fs);"
    write(unit_script,'(a)') ""
    write(unit_script,'(a)') "nexttile; imagesc(z, x, squeeze(u(:,j1,:))); axis image; axis xy; caxis([umin umax]);"
    write(unit_script,'(a)') "title(sprintf('$y = %.3f\\,[\\mathrm{m}]$', y(j1)), 'Interpreter','latex', 'FontSize', fs);"
    write(unit_script,'(a)') "xlabel('$z \quad [\mathrm{m}]$', 'Interpreter','latex', 'FontSize', fs); ylabel('$x \quad [\mathrm{m}]$', 'Interpreter','latex', 'FontSize', fs);"
    write(unit_script,'(a)') "set(gca, 'TickLabelInterpreter','latex', 'FontSize', fs);"
    write(unit_script,'(a)') ""
    write(unit_script,'(a)') "nexttile; imagesc(y, x, u(:,:,k1)); axis image; axis xy; caxis([umin umax]);"
    write(unit_script,'(a)') "title(sprintf('$z = %.3f\\,[\\mathrm{m}]$', z(k1)), 'Interpreter','latex', 'FontSize', fs);"
    write(unit_script,'(a)') "xlabel('$y \quad [\mathrm{m}]$', 'Interpreter','latex', 'FontSize', fs); ylabel('$x \quad [\mathrm{m}]$', 'Interpreter','latex', 'FontSize', fs);"
    write(unit_script,'(a)') "set(gca, 'TickLabelInterpreter','latex', 'FontSize', fs);"
    write(unit_script,'(a)') ""
    write(unit_script,'(a)') "% Row 2: 2/3 slices"
    write(unit_script,'(a)') "nexttile; imagesc(z, y, squeeze(u(i2,:,:))); axis image; axis xy; caxis([umin umax]);"
    write(unit_script,'(a)') "title(sprintf('$x = %.3f\\,[\\mathrm{m}]$', x(i2)), 'Interpreter','latex', 'FontSize', fs);"
    write(unit_script,'(a)') "xlabel('$z \quad [\mathrm{m}]$', 'Interpreter','latex', 'FontSize', fs); ylabel('$y \quad [\mathrm{m}]$', 'Interpreter','latex', 'FontSize', fs);"
    write(unit_script,'(a)') "set(gca, 'TickLabelInterpreter','latex', 'FontSize', fs);"
    write(unit_script,'(a)') ""
    write(unit_script,'(a)') "nexttile; imagesc(z, x, squeeze(u(:,j2,:))); axis image; axis xy; caxis([umin umax]);"
    write(unit_script,'(a)') "title(sprintf('$y = %.3f\\,[\\mathrm{m}]$', y(j2)), 'Interpreter','latex', 'FontSize', fs);"
    write(unit_script,'(a)') "xlabel('$z \quad [\mathrm{m}]$', 'Interpreter','latex', 'FontSize', fs); ylabel('$x \quad [\mathrm{m}]$', 'Interpreter','latex', 'FontSize', fs);"
    write(unit_script,'(a)') "set(gca, 'TickLabelInterpreter','latex', 'FontSize', fs);"
    write(unit_script,'(a)') ""
    write(unit_script,'(a)') "nexttile; imagesc(y, x, u(:,:,k2)); axis image; axis xy; caxis([umin umax]);"
    write(unit_script,'(a)') "title(sprintf('$z = %.3f\\,[\\mathrm{m}]$', z(k2)), 'Interpreter','latex', 'FontSize', fs);"
    write(unit_script,'(a)') "xlabel('$y \quad [\mathrm{m}]$', 'Interpreter','latex', 'FontSize', fs); ylabel('$x \quad [\mathrm{m}]$', 'Interpreter','latex', 'FontSize', fs);"
    write(unit_script,'(a)') "set(gca, 'TickLabelInterpreter','latex', 'FontSize', fs);"
    write(unit_script,'(a)') ""
    write(unit_script,'(a)') "% One shared colorbar for all tiles"
    write(unit_script,'(a)') "cb = colorbar;"
    write(unit_script,'(a)') "cb.Layout.Tile = 'east';"
    write(unit_script,'(a)') "ylabel(cb, 'Temperature $[^{\circ}\mathrm{C}]$', 'Interpreter','latex', 'FontSize', fs);"
    write(unit_script,'(a)') "set(cb, 'TickLabelInterpreter','latex', 'FontSize', fs);"
    write(unit_script,'(a)') ""
    write(unit_script,'(a)') "% Save figure to current folder"
    write(unit_script,'(a)') "outPng = fullfile(pwd, 'poisson_sol_slices.png');"
    write(unit_script,'(a)') "if exist('exportgraphics', 'file')"
    write(unit_script,'(a)') "    exportgraphics(gcf, outPng, 'Resolution', 300);"
    write(unit_script,'(a)') "else"
    write(unit_script,'(a)') "    set(gcf, 'PaperPositionMode', 'auto');"
    write(unit_script,'(a)') "    print(gcf, outPng, '-dpng', '-r300');"
    write(unit_script,'(a)') "end"

    close(unit_script)
  end subroutine write_matlab

end module write_output
