module write_output
  use precision, only: dp

  implicit none
  private

  public :: write_binary
  public :: write_vtk
  public :: write_matlab

contains

  subroutine check_iostat_local(iostat, msg)
    integer, intent(in) :: iostat
    character(len=*), intent(in) :: msg

    if ( iostat == 0 ) return

    write(*,'(a,i0,/,tr3,a)') 'ERROR = ', iostat, msg
    stop
  end subroutine check_iostat_local

  subroutine write_binary(u)
    real(dp), intent(in) :: u(:,:,:)

    character(len=*), parameter :: filename = 'output/poisson_u.bin'
    integer :: n
    integer :: iostat

    integer, parameter :: unit = 11249

    n = size(u, 1)

    open(unit, file=filename, form='unformatted', access='stream', status='replace', iostat=iostat)
    call check_iostat_local(iostat, "Could not open file '"//filename//"'!")

    write(unit, iostat=iostat) n
    call check_iostat_local(iostat, 'Could not write variable N')

    write(unit, iostat=iostat) u
    call check_iostat_local(iostat, 'Could not write variable u')

    close(unit)
  end subroutine write_binary

  subroutine write_vtk(u)
    use, intrinsic :: iso_c_binding

    interface
      subroutine write_vtk_c(n, u) bind(C, name='write_vtk')
        import c_ptr, c_int
        implicit none
        integer(c_int), value :: n
        type(c_ptr), value :: u
      end subroutine write_vtk_c
    end interface

    real(dp), intent(in), target :: u(:,:,:)

    integer(c_int) :: n

    n = size(u, 1)
    call write_vtk_c(n, c_loc(u(1,1,1)))
  end subroutine write_vtk

  subroutine write_matlab(u)
    use, intrinsic :: iso_fortran_env, only: int32

    real(dp), intent(in) :: u(:,:,:)

    character(len=*), parameter :: data_filename = 'output/poisson_u_matlab.bin'
    character(len=*), parameter :: script_filename = 'output/plot_poisson_u.m'

    integer(int32) :: n
    integer :: iostat

    integer, parameter :: unit_data = 21249
    integer, parameter :: unit_script = 21250

    n = int(size(u, 1), int32)

    ! Write a MATLAB-friendly binary file:
    ! - int32: N
    ! - double: u(:,:,:) in Fortran (column-major) order
    open(unit_data, file=data_filename, form='unformatted', access='stream', status='replace', iostat=iostat)
    call check_iostat_local(iostat, "Could not open file '"//data_filename//"'!")

    write(unit_data, iostat=iostat) n
    call check_iostat_local(iostat, 'Could not write variable N')

    write(unit_data, iostat=iostat) u
    call check_iostat_local(iostat, 'Could not write variable u')

    close(unit_data)

    ! Write a companion MATLAB script that loads and visualizes the 3D field.
    open(unit_script, file=script_filename, action='write', status='replace', iostat=iostat)
    call check_iostat_local(iostat, "Could not open file '"//script_filename//"'!")

    write(unit_script,'(a)') "% Auto-generated by poisson3d/write_matlab"
    write(unit_script,'(a)') "% Usage: from MATLAB, run this script: plot_poisson_u"
    write(unit_script,'(a)') "scriptDir = fileparts(mfilename('fullpath'));"
    write(unit_script,'(a)') "dataFile  = fullfile(scriptDir, 'poisson_u_matlab.bin');"
    write(unit_script,'(a)') "fid = fopen(dataFile, 'rb');"
    write(unit_script,'(a)') "assert(fid > 0, 'Could not open %s', dataFile);"
    write(unit_script,'(a)') "N = fread(fid, 1, 'int32');"
    write(unit_script,'(a)') "u = fread(fid, double(N)^3, 'double');"
    write(unit_script,'(a)') "fclose(fid);"
    write(unit_script,'(a)') "u = reshape(u, [N N N]);"
    write(unit_script,'(a)') ""
    write(unit_script,'(a)') "% Basic 3D visualization: isosurface + mid-plane slices"
    write(unit_script,'(a)') "figure('Name','poisson3d: u');"
    write(unit_script,'(a)') "subplot(1,2,1);"
    write(unit_script,'(a)') "iso = 0.5*(min(u(:)) + max(u(:)));"
    write(unit_script,'(a)') "p = patch(isosurface(u, iso));"
    write(unit_script,'(a)') "isonormals(u, p);"
    write(unit_script,'(a)') "set(p, 'FaceColor', [0.2 0.6 0.9], 'EdgeColor', 'none', 'FaceAlpha', 0.6);"
    write(unit_script,'(a)') "daspect([1 1 1]); axis tight; view(3); grid on;"
    write(unit_script,'(a)') "camlight headlight; lighting gouraud;"
    write(unit_script,'(a)') "title(sprintf('Isosurface u = %.3g', iso));"
    write(unit_script,'(a)') ""
    write(unit_script,'(a)') "subplot(1,2,2);"
    write(unit_script,'(a)') "k = round(N/2);"
    write(unit_script,'(a)') "imagesc(u(:,:,k)); axis image; colorbar;"
    write(unit_script,'(a)') "title(sprintf('Mid-plane slice k=%d', k));"

    close(unit_script)
  end subroutine write_matlab

end module write_output
